### ISSUE TITLE
WARNING, Binance credentials

### ISSUE THREAD

**Issue by crystalin** [hsichen/crypto-trade-bot#1]
You left your credential in the file binance.js, using those credential someone could steal your money !!
I suggest you delete this repository

const crudentials = {
    APIKey : "DeGd9efTIYzr......",
    APISecret : "nlrWarGLBoXct......"
};

**Comment by hsichen** [comment]
That you for the notice!!! I've deleted those keys now on the exchanges, fortunately didn't have withdraw permissions anyway.
